作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [15]:
import numpy as np

In [24]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [4, 5]])
print(array1,"\n")


array_inv=np.linalg.inv(array1)
print(array_inv,"\n")

aa=np.matmul(array_inv,array1)
print(aa,"\n")


[[10  8]
 [ 4  5]] 

[[ 0.27777778 -0.44444444]
 [-0.22222222  0.55555556]] 

[[ 1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00]] 



In [28]:
#2. 運用上列array計算特徵值、特徵向量?
array_eig = np.linalg.eig(array1)
print("eig:",array_eig,"\n") 
array_eig = np.linalg.eigvals(array1)
print("eig values:",array_eig,"\n") 

eig: (array([13.68465844,  1.31534156]), array([[ 0.90828954, -0.67752031],
       [ 0.41834209,  0.73550406]])) 

eig values: [13.68465844  1.31534156] 



In [31]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
print("U:",u,"\n")
print("S:",s,"\n")
print("vh:",vh,"\n")

U: [[-0.89707059 -0.44188728]
 [-0.44188728  0.89707059]] 

S: [14.26208735  1.26208735] 

vh: [[-0.7529231  -0.65810851]
 [-0.65810851  0.7529231 ]] 

